name: Respond to Update

on:
  repository_dispatch:
    types: [update-plugin]

jobs:
  update-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update plugin in pluginmaster.json
        run: |
          const fs = require('fs');
          const pluginName = 'NNKicker';
          const version = '${{ github.event.client_payload.tag }}';
          const downloadUrl = '${{ github.event.client_payload.url }}';
          const path = 'pluginmaster.json';

          const content = fs.readFileSync(path, 'utf8');
          const json = JSON.parse(content);

          const item = json.plugins.find(p => p.Name === pluginName);
          if (item) {
            item.DownloadLinkInstall = downloadUrl;
            item.DownloadLinkTesting = downloadUrl;
            item.DownloadLinkUpdate = downloadUrl;
            item.Version = version;
          }

          fs.writeFileSync(path, JSON.stringify(json, null, 2));
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
