name: UpdatePluginmaster-Repo

on:
  repository_dispatch:
    types: [update-plugin]

jobs:
  update-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update plugin in pluginmaster.json
        run: node update-plugin.js
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          URL: ${{ github.event.client_payload.url }}
          DOWNLOAD_COUNT: ${{ github.event.client_payload.downloadcount }}
          AUTHOR: ${{ github.event.client_payload.author }}
          NAME: ${{ github.event.client_payload.name }}
          INTERNAL_NAME: ${{ github.event.client_payload.internalname }}
          ASSEMBLY_VERSION: ${{ github.event.client_payload.assemblyversion }}
          DESCRIPTION: ${{ github.event.client_payload.description }}
          REPO_URL: ${{ github.event.client_payload.repourl }}
          PUNCHLINE: ${{ github.event.client_payload.punchline }}

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update ${{ github.event.client_payload.name }} to ${{ github.event.client_payload.assemblyversion }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
